import json
from pathlib import Path
from typing import Set
from unittest import TestCase, skipUnless

from compile_kaitai_parsers import KAITAI_FORMAT_LIBRARY, MANIFEST_PATH, excluded_specs, spec_license

POLYFILE_DIR: Path = Path(__file__).absolute().parent.parent
MANIFEST_IN_PATH: Path = POLYFILE_DIR / "MANIFEST.in"
PARSERS_DIR: Path = MANIFEST_PATH.parent

HAVE_FORMAT_LIBRARY: bool = KAITAI_FORMAT_LIBRARY.is_dir() and any(KAITAI_FORMAT_LIBRARY.glob("**/*.ksy"))


def manifest_in_exclusions() -> Set[str]:
    """Reads the specifications that MANIFEST.in keeps out of the source distribution."""
    prefix = "exclude kaitai_struct_formats/"
    return {
        line[len(prefix):].strip()
        for line in MANIFEST_IN_PATH.read_text().splitlines()
        if line.startswith(prefix)
    }


@skipUnless(HAVE_FORMAT_LIBRARY, "the kaitai_struct_formats submodule is not checked out")
class TestKaitaiLicensing(TestCase):
    """Guards the rule that PolyFile only redistributes permissively licensed Kaitai specifications.

    A parser generated by the Kaitai Struct compiler is a derivative work of the specification it
    was generated from, so shipping one built from a copyleft specification would put the Apache 2.0
    distribution out of compliance. These tests fail if such a parser reaches the package, or if the
    source distribution stops agreeing with the compiler about which specifications are excluded.
    """

    def setUp(self):
        self.excluded = excluded_specs()
        self.assertTrue(self.excluded, "expected at least one non-permissive specification")

    def test_manifest_lists_only_permissive_specs(self):
        with open(MANIFEST_PATH, "r") as f:
            manifest = json.load(f)
        for relative_path in manifest:
            with self.subTest(spec=relative_path):
                self.assertIsNotNone(
                    spec_license(KAITAI_FORMAT_LIBRARY / relative_path),
                    f"{relative_path} is in the parser manifest but declares no license"
                )
                self.assertNotIn(KAITAI_FORMAT_LIBRARY / relative_path, self.excluded)

    def test_no_parser_is_generated_from_an_excluded_spec(self):
        generated = {path.stem for path in PARSERS_DIR.glob("*.py")}
        for spec, license_name in self.excluded.items():
            with self.subTest(spec=str(spec.relative_to(KAITAI_FORMAT_LIBRARY))):
                self.assertNotIn(
                    spec.stem, generated,
                    f"{spec.stem}.py is generated from {spec.name}, which is licensed "
                    f"{license_name or 'not at all'}"
                )

    def test_source_distribution_excludes_the_same_specs(self):
        expected = {str(spec.relative_to(KAITAI_FORMAT_LIBRARY)) for spec in self.excluded}
        self.assertEqual(
            expected, manifest_in_exclusions(),
            "MANIFEST.in and compile_kaitai_parsers.excluded_specs() disagree about which "
            "specifications PolyFile may redistribute"
        )
