from abnf.grammars.misc import load_grammar_rulelist
from abnf.grammars import rfc9110, rfc5322, rfc4647, rfc5646, rfc3986
from abnf import Rule, parser

from .polyfile import register_parser, InvalidMatch, Submatch

# Goals: "parse HTTP"
#   - parse HTTP requests from utf-8 text file(s) with abnf
#   - parse HTTP requests (and streams) from pcaps with dpkt.
#   - maybe use this input to feed abnf parser if it's not a dupe step??
#   - maybe: expand from HTTP 1.1 to HTTP 2 (requires parsing HPACK and QPACK, but might be easy with dpkt, scapy, etc?)

# Textual Input
# ???

# PCAP
# Samples from NetReSec: https://www.netresec.com/?page=PcapFiles
# Sample captures from WireShark: https://wiki.wireshark.org/SampleCaptures
# "the ultimate PCAP" https://weberblog.net/the-ultimate-pcap/

rulelist = [
    ("Accept", rfc9110.Rule("Accept")),
    ("Accept-Charset", rfc9110.Rule("Accept-Charset")),
    ("Accept-Encoding", rfc9110.Rule("Accept-Encoding")),
    ("Accept-Language", rfc9110.Rule("Accept-Language")),
    ("Accept-Ranges", rfc9110.Rule("Accept-Ranges")),
    ("Allow", rfc9110.Rule("Allow")),
    ("Authentication-Info", rfc9110.Rule("Authentication-Info")),
    ("Authorization", rfc9110.Rule("Authorization")),
    ("BWS", rfc9110.Rule("BWS")),
    ("Connection", rfc9110.Rule("Connection")),
    ("Content-Encoding", rfc9110.Rule("Content-Encoding")),
    ("Content-Language", rfc9110.Rule("Content-Language")),
    ("Content-Length", rfc9110.Rule("Content-Length")),
    ("Content-Location", rfc9110.Rule("Content-Location")),
    ("Content-Range", rfc9110.Rule("Content-Range")),
    ("Content-Type", rfc9110.Rule("Content-Type")),
    ("Date", rfc9110.Rule("Date")),
    ("ETag", rfc9110.Rule("ETag")),
    ("Expect", rfc9110.Rule("Expect")),
    ("From", rfc5322.Rule("mailbox")),
    ("GMT", rfc9110.Rule("GMT")),
    ("HTTP-date", rfc9110.Rule("HTTP-date")),
    ("IMF-fixdate", rfc9110.Rule("IMF-fixdate")),
    ("If-Match", rfc9110.Rule("If-Match")),
    ("If-Modified-Since", rfc9110.Rule("If-Modified-Since")),
    ("If-None-Match", rfc9110.Rule("If-None-Match")),
    ("If-Range", rfc9110.Rule("If-Range")),
    ("If-Unmodified-Since", rfc9110.Rule("If-Unmodified-Since")),
    ("Last-Modified", rfc9110.Rule("Last-Modified")),
    ("Location", rfc9110.Rule("Location")),
    ("Max-Forwards", rfc9110.Rule("Max-Forwards")),
    ("OWS", rfc9110.Rule("OWS")),
    ("Proxy-Authenticate", rfc9110.Rule("Proxy-Authenticate")),
    ("Proxy-Authentication-Info", rfc9110.Rule("Proxy-Authentication-Info")),
    ("Proxy-Authorization", rfc9110.Rule("Proxy-Authorization")),
    ("RWS", rfc9110.Rule("RWS")),
    ("Range", rfc9110.Rule("Range")),
    ("Referer", rfc9110.Rule("Referer")),
    ("Retry-After", rfc9110.Rule("Retry-After")),
    ("Server", rfc9110.Rule("Server")),
    ("TE", rfc9110.Rule("TE")),
    ("Trailer", rfc9110.Rule("Trailer")),
    ("URI-reference", rfc3986.Rule("URI-reference")),
    ("Upgrade", rfc9110.Rule("Upgrade")),
    ("User-Agent", rfc9110.Rule("User-Agent")),
    ("Vary", rfc9110.Rule("Vary")),
    ("Via", rfc9110.Rule("Via")),
    ("WWW-Authenticate", rfc9110.Rule("WWW-Authenticate")),
    ("absolute-URI", rfc3986.Rule("absolute-URI")),
    ("absolute-path", rfc9110.Rule("absolute-path")),
    ("acceptable-ranges", rfc9110.Rule("acceptable-ranges")),
    ("asctime-date", rfc9110.Rule("asctime-date")),
    ("auth-param", rfc9110.Rule("auth-param")),
    ("auth-scheme", rfc9110.Rule("auth-scheme")),
    ("authority", rfc3986.Rule("authority")),
    ("challenge", rfc9110.Rule("challenge")),
    ("codings", rfc9110.Rule("codings")),
    ("comment", rfc9110.Rule("comment")),
    ("complete-length", rfc9110.Rule("complete-length")),
    ("connection-option", rfc9110.Rule("connection-option")),
    ("content-coding", rfc9110.Rule("content-coding")),
    ("credentials", rfc9110.Rule("credentials")),
    ("ctext", rfc9110.Rule("ctext")),
    ("date1", rfc9110.Rule("date1")),
    ("date2", rfc9110.Rule("date2")),
    ("date3", rfc9110.Rule("date3")),
    ("day", rfc9110.Rule("day")),
    ("day-name", rfc9110.Rule("day-name")),
    ("day-name-l", rfc9110.Rule("day-name-l")),
    ("delay-seconds", rfc9110.Rule("delay-seconds")),
    ("entity-tag", rfc9110.Rule("entity-tag")),
    ("etagc", rfc9110.Rule("etagc")),
    ("expectation", rfc9110.Rule("expectation")),
    ("field-content", rfc9110.Rule("field-content")),
    ("field-name", rfc9110.Rule("field-name")),
    ("field-value", rfc9110.Rule("field-value")),
    ("field-vchar", rfc9110.Rule("field-vchar")),
    ("first-pos", rfc9110.Rule("first-pos")),
    ("hour", rfc9110.Rule("hour")),
    ("http-URI", rfc9110.Rule("http-URI")),
    ("https-URI", rfc9110.Rule("https-URI")),
    ("incl-range", rfc9110.Rule("incl-range")),
    ("int-range", rfc9110.Rule("int-range")),
    ("language-range", rfc4647.Rule("language-range")),
    ("language-tag", rfc5646.Rule("language-tag")),
    ("last-pos", rfc9110.Rule("last-pos")),
    ("mailbox", rfc5322.Rule("mailbox")),
    ("media-range", rfc9110.Rule("media-range")),
    ("media-type", rfc9110.Rule("method")),
    ("minute", rfc9110.Rule("minute")),
    ("month", rfc9110.Rule("month")),
    ("obs-date", rfc9110.Rule("obs-date")),
    ("obs-text", rfc9110.Rule("obs-text")),
    ("opaque-tag", rfc9110.Rule("opaque-tag")),
    ("other-range", rfc9110.Rule("other-range")),
    ("parameter", rfc9110.Rule("parameter")),
    ("parameter-name", rfc9110.Rule("parameter-name")),
    ("parameter-value", rfc9110.Rule("parameter-value")),
    ("parameters", rfc9110.Rule("parameters")),
    ("partial-URI", rfc9110.Rule("partial-URI")),
    ("path-abempty", rfc3986.Rule("path-abempty")),
    ("port", rfc3986.Rule("port")),
    ("product", rfc9110.Rule("product")),
    ("product-version", rfc9110.Rule("product-version")),
    ("protocol", rfc9110.Rule("protocol")),
    ("protocol-name", rfc9110.Rule("protocol-name")),
    ("protocol-version", rfc9110.Rule("protocol-version")),
    ("pseudonym", rfc9110.Rule("pseudonym")),
    ("qdtext", rfc9110.Rule("qdtext")),
    ("query", rfc3986.Rule("query")),
    ("quoted-pair", rfc9110.Rule("quoted-pair")),
    ("quoted-string", rfc9110.Rule("quoted-string")),
    ("qvalue", rfc9110.Rule("qvalue")),
    ("range-resp", rfc9110.Rule("range-resp")),
    ("range-set", rfc9110.Rule("range-set")),
    ("range-spec", rfc9110.Rule("range-spec")),
    ("range-unit", rfc9110.Rule("range-unit")),
    ("ranges-specifier", rfc9110.Rule("ranges-specifier")),
    ("received-by", rfc9110.Rule("received-by")),
    ("received-protocol", rfc9110.Rule("received-protocol")),
    ("relative-part", rfc3986.Rule("relative-part")),
    ("rfc850-date", rfc9110.Rule("rfc850-date")),
    ("second", rfc9110.Rule("second")),
    ("segment", rfc3986.Rule("segment")),
    ("subtype", rfc9110.Rule("subtype")),
    ("suffix-length", rfc9110.Rule("suffix-length")),
    ("suffix-range", rfc9110.Rule("suffix-range")),
    ("t-codings", rfc9110.Rule("t-codings")),
    ("tchar", rfc9110.Rule("tchar")),
    ("time-of-day", rfc9110.Rule("time-of-day")),
    ("token", rfc9110.Rule("token")),
    ("token68", rfc9110.Rule("token68")),
    ("transfer-coding", rfc9110.Rule("transfer-coding")),
    ("transfer-parameter", rfc9110.Rule("transfer-parameter")),
    ("type", rfc9110.Rule("type")),
    ("unsatisfied-range", rfc9110.Rule("unsatisfied-range")),
    ("uri-host", rfc3986.Rule("host")),
    ("weak", rfc9110.Rule("weak")),
    ("weight", rfc9110.Rule("weight")),
    ("year", rfc9110.Rule("year")),
]


@load_grammar_rulelist(rulelist)
class HttpStringParser(Rule, parser.NodeVisitor):
    def __init__(self):
        super().__init__()

    def parse_http(self, input: str):
        ast, offset = self.parse(input, 0)
        self.visit(ast)
